config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?

  root to: 'codes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :codes do
    resources :drafts
    resources :likes
    resources :dislikes
    resources :histories
  end
  resources :codes
  namespace :users do
    resources :profiles
    resources :change_passwords
    resources :follow_tags
  end
  namespace :reviews do
    resources :resolutions
  end
  resources :reviews
  namespace :comments do
    resources :resolutions
  end
  resources :comments
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FlashValidatable

  attr_accessor :current_password, :new_password, :new_password_confirmation

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[github google]

  flash_validation :reset_password_token

  has_many :user_codes
  has_many :user_code_likes
  has_many :user_code_dislikes
  has_many :comments
  has_many :user_tags
  has_many :tags, through: :user_tags

  has_one_attached :icon

  validates :name, presence: true, on: :profile
  validates :description, length: { maximum: 255 }, on: :profile
  validates :tags, presence: true, on: :follow_tags

  with_options on: :change_password do
    validates :current_password, presence: true
    validates :new_password, presence: true
    validates :new_password_confirmation, presence: true
  end

  before_save do
    self.name = email.match(/.*(?=@)/).to_s if new_record?
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def update_profile(user_params)
    assign_attributes(user_params)
    save(context: :profile)
  end

  def posted_codes
    UserCode.includes(:tags).where(user_id: id).order(created_at: :desc).limit(10)
  end

  def liked_codes
    code_ids = UserCodeLike.where(user_id: id).pluck(:user_code_id)
    UserCode.where(id: code_ids)
  end

  def reviewed_codes
    code_ids = Review.where(user_id: id).pluck(:code_id).uniq
    Code.includes(:user_code).where(id: code_ids)&.map(&:user_code)
  end

  def change_password(user_params)
    assign_attributes(user_params)
    return false unless valid_password?(current_password)

    valid?(:change_password)
    reset_password(new_password, new_password_confirmation)
  end

  def sns_registration?
    provider.present?
  end

  def icon_url
    return unless icon&.attached?

    Rails.application.routes.url_helpers.rails_blob_path(icon, disposition: 'attachment', only_path: true)
  end

  def attributes
    hash = super
    hash['icon_url'] = icon_url
    hash
  end

  def follow_tags(tag_names)
    transaction do
      self.tags = tag_names.map do |name|
        Tag.find_or_create_by(name: name)
      end
      save!(context: :follow_tags)
    end
  rescue ActiveRecord::RecordInvalid
    false
  end
end

app/controllers/users/change_passwords_controller.rb
# frozen_string_literal: true

class Users::ChangePasswordsController < ApplicationController
  before_action :authenticate_user!

  def update
    @user = User.find(params[:id])
    if @user.change_password(user_params)
      flash[:success] = t('saved')
    else
      flash[:alert] = t('errors.invalid')
    end
    render 'users/profiles/edit'
  end

  private

  def user_params
    params.require(:user).permit(:current_password, :new_password, :new_password_confirmation)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(_resource_name, resource)
    sign_in(resource)
    new_users_follow_tag_path
  end
end

app/controllers/users/follow_tags_controller.rb
# frozen_string_literal: true

class Users::FollowTagsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tags = Tag.all
  end

  def create
    params[:tags] ||= []
    if current_user.follow_tags(params[:tags])
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def google
    callback_from :google
  end

  def github
    callback_from :github
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to new_user_session_path
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
# frozen_string_literal: true

class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id]).decorate
  end

  def edit
    @user = User.find(params[:id]).decorate
  end

  def update
    @user = User.find(params[:id])
    if @user.update_profile(user_params)
      flash.now[:success] = t('saved')
    else
      flash.now[:alert] = t('errors.invalid')
    end
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:name, :description, :email, :icon)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(_resource)
    new_user_registration_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/change_passwords_helper.rb
# frozen_string_literal: true

module Users::ChangePasswordsHelper
end

app/helpers/users/follow_tags_helper.rb
# frozen_string_literal: true

module Users::FollowTagsHelper
end

app/helpers/users/profiles_helper.rb
# frozen_string_literal: true

module Users::ProfilesHelper
end

app/views/users/profiles/_change_email_form.html.slim
.change-email-form
  = form_with model: @user, url: users_profile_path, method: :put, builder: RefineFormBuilder, local: true do |f|

    - if @user.pending_reconfirmation?
      .uk-alert-primary.uk-margin[uk-alert]
        = t('messages.confirming_email')

    .new-email
      = f.label t('new_email'), for: :user_email
      = f.email_field_with_icon :email, class: 'uk-input'

    .uk-submit.uk-text-center.uk-margin
      = f.submit t('save'), class: 'uk-button uk-button-primary'

app/views/users/profiles/_change_password_form.html.slim
.change-password-form
  = form_with model: @user, url: users_change_password_path, method: :put, builder: RefineFormBuilder, local: true do |f|
    input[id="userName" name="username" autocomplete="username" value=""]

    .current-password.uk-margin
      = f.label :current_password
      = f.password_field_with_icon :current_password, class: 'uk-input', autocomplete: 'current-password'

    .new-password.uk-margin
      = f.label :new_password
      = f.password_field_with_icon :new_password, class: 'uk-input', autocomplete: 'new-password'

    .new-password-confirmation.uk-margin
      = f.label :new_password_confirmation
      = f.password_field_with_icon :new_password_confirmation, class: 'uk-input', autocomplete: 'new-password'

    .uk-submit.uk-text-center.uk-margin
      = f.submit t('save'), class: 'uk-button uk-button-primary'

app/views/users/profiles/_profile_form.html.slim
.profile-form
  = form_with model: @user, url: users_profile_path, method: :put, builder: RefineFormBuilder, local: true, multipart: true do |f|
    icon-uploader[
      image-source=@user.icon_url
    ]

    .user-name.uk-margin
      = f.label :name
      = f.text_field :name, class: 'uk-input'

    .description.uk-margin
      = f.label :description
      = f.text_area :description, class: 'uk-textarea', rows: 10

    .uk-submit.uk-text-center.uk-margin
      = f.submit t('save'), class: 'uk-button uk-button-primary'

app/views/users/profiles/edit.html.slim
.uk-container
  .edit-profile.uk-margin-top
    = render partial: 'shared/flash_messages'

    ul.uk-tab-right.uk-width-1-4.uk-inline-block.vertical-top[uk-tab uk-switcher]
      li.uk-active
        = link_to t('profile'), '#'
      li
        = link_to t('email'), '#'
      - unless @user.sns_registration?
        li
          = link_to t('password'), '#'

    ul.uk-switcher.uk-width-3-4.uk-inline-block
      li
        = render partial: 'users/profiles/profile_form'
      li
        = render partial: 'users/profiles/change_email_form'
      li
        = render partial: 'users/profiles/change_password_form'

app/views/users/profiles/show.html.slim
#profile.uk-container
  .user-profile[uk-grid]
    .user-information.uk-width-1-4.uk-margin-top
      .icon.uk-text-center.uk-margin
        = image_tag @user.attached_icon
      .user-detail.uk-text-left.uk-text-large.uk-margin
        span.user-name
          = "@#{@user.name}"
      .user-description.uk-margin
        p
          = @user.description
      .following-tags.uk-margin
        span = t('tag.following')
        .tags.uk-margin-small-top
          tag[label="Rails"]
          tag[label="Ruby"]
          tag[label="Python"]
          tag[label="C++"]
          tag[label="Swift"]
          tag[label="Rust"]

      .edit-profile
        = link_to t('edit_profile'), edit_users_profile_path

    .activity.uk-width-3-4
      .graph.uk-text-center.uk-margin.uk-margin-top
        = image_tag 'graph.png', class: 'uk-width-1-2'
      .tabs
        ul.uk-child-width-expand[uk-tab uk-switcher]
          li.uk-active
            a = t('post')
          li
            a = t('good')
          li
            a = t('review')

        ul.uk-switcher.uk-margin
          li.posted
            ul.code-list
              - @user.posted_codes.each do |code|
                li.uk-margin
                  .uk-flex
                    .status.uk-width-1-6.uk-text-center
                      large-badge[label=code.status_text]
                      review-info
                    .information.uk-width-4-6.uk-margin-left
                      = link_to code.title, code_path(id: code.id), class: 'uk-text-large'
                      .tags.uk-margin-top
                        - code.tags.each do |tag|
                          tag[label=tag.name]

                    .user.uk-width-1-6
                      .user-name.uk-text-right
                        span = code.user.name
                  hr

          li.good
            ul.code-list
              - @user.liked_codes.each do |code|
                li.uk-margin
                  .uk-flex
                    .status.uk-width-1-6.uk-text-center
                      large-badge[label=code.status_text]
                      review-info
                    .information.uk-width-4-6.uk-margin-left
                      = link_to code.title, code_path(id: code.id), class: 'uk-text-large'
                      .tags.uk-margin-top
                        - code.tags.each do |tag|
                          tag[label=tag.name]

                    .user.uk-width-1-6
                      .user-name.uk-text-right
                        span = code.user.name
                  hr

          li.reviews
            ul.code-list
              - @user.reviewed_codes.each do |code|
                li.uk-margin
                  .uk-flex
                    .status.uk-width-1-6.uk-text-center
                      large-badge[label=code.status_text]
                      review-info
                    .information.uk-width-4-6.uk-margin-left
                      = link_to code.title, code_path(id: code.id), class: 'uk-text-large'
                      .tags.uk-margin-top
                        - code.tags.each do |tag|
                          tag[label=tag.name]

                    .user.uk-width-1-6
                      .user-name.uk-text-right
                        span = code.user.name
                  hr