config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?

  root to: 'codes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :codes do
    resources :drafts
    resources :likes
    resources :dislikes
    resources :histories
  end
  resources :codes
  namespace :users do
    resources :profiles
    resources :change_passwords
    resources :follow_tags
  end
  namespace :reviews do
    resources :resolutions
  end
  resources :reviews
  namespace :comments do
    resources :resolutions
  end
  resources :comments
end

app/views/shared/_flash_messages.html.slim
- flash.each do |key, value|
  - case key.to_sym
  - when :alert

    .uk-alert-danger[uk-alert]
      a.uk-alert-close[uk-close]
      .uk-text-small = value
  - when :notice

    .uk-alert-primary[uk-alert]
      a.uk-alert-close[uk-close]
      .uk-text-small = value
  - else

    .uk-alert-success[uk-alert]
      a.uk-alert-close[uk-close]
      .uk-text-small = value

app/views/shared/_header.html.slim
nav.uk-light#nav-bar[uk-navbar]
  .uk-navbar-left.uk-margin-left
    ul.uk-navbar-nav
      li.uk-active
        = link_to t('title'), root_path

  .uk-navbar-right.uk-margin-right
    .search-form.uk-hidden-touch
      a.uk-navbar-toggle[uk-search-icon]
      .uk-drop[uk-drop="mode: click; pos: left-center; offset: 0"]
        form.uk-search.uk-search-navbar.uk-width-1-1
          = search_field_tag :search, '', autofocus: true, class: 'uk-search-input', placeholder: t('search')

    .uk-navbar-nav
      .uk-navbar-item
        - if user_signed_in?
          a.uk-navbar-toggle[uk-navbar-toggle-icon uk-toggle="target: #offcanvas"]

          = render partial: 'shared/side_nav'

        - else
          = link_to t('register'), new_user_registration_path, class: 'uk-button uk-button-primary uk-button-small'
          = link_to t('login'), new_user_session_path, class: 'uk-button uk-button-default uk-button-small uk-margin-left'

app/views/shared/_side_nav.html.slim
#offcanvas[uk-offcanvas="flip: true; overlay: true"]
  .uk-offcanvas-bar
    button.uk-offcanvas-close[uk-close]
    ul.uk-list
      li
        = link_to t('profile'), users_profile_path(id: current_user.id), class: 'uk-link'
      li
        = link_to t('post_code'), new_code_path, class: 'uk-link'
      li
        = link_to t('posted_codes'), '#', class: 'uk-link'
      li
        = link_to t('drafts'), codes_drafts_path, class: 'uk-link'
      li
        = link_to t('logout'), destroy_user_session_path, method: :delete, class: 'uk-link'