config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letters' if Rails.env.development?

  root to: 'codes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :codes do
    resources :drafts
    resources :likes
    resources :dislikes
    resources :histories
  end
  resources :codes
  namespace :users do
    resources :profiles
    resources :change_passwords
    resources :follow_tags
  end
  namespace :reviews do
    resources :resolutions
  end
  resources :reviews
  namespace :comments do
    resources :resolutions
  end
  resources :comments
end

app/models/code.rb
# frozen_string_literal: true

class Code < ApplicationRecord
  extend Enumerize

  belongs_to :language
  belongs_to :user_code

  has_many :reviews

  validates :code, presence: true, unless: -> { validation_context == :draft }

  def self.review_count
    all.sum do |code|
      code.reviews.count
    end
  end
end

app/controllers/codes/dislikes_controller.rb
# frozen_string_literal: true

class Codes::DislikesController < ApplicationController
  protect_from_forgery except: %i[create destroy]
  before_action :authenticate_user!

  def create
    code = UserCode.find(params[:code_id])
    like = UserCodeDislike.new(user: current_user, user_code: code)
    like.save!
    render json: { status: :success }
  rescue StandardError => e
    logger.error e
    render json: { status: :error }
  end

  def destroy
    dislike = UserCodeDislike.find_by(user_code_id: params[:id], user_id: current_user.id)
    dislike.destroy!
    render json: { status: :success }
  rescue StandardError => e
    logger.error e
    render json: { status: :error }
  end
end

app/controllers/codes/drafts_controller.rb
# frozen_string_literal: true

class Codes::DraftsController < ApplicationController
  include CodePermittable

  before_action :authenticate_user!
  before_action :verify_valid_user, only: %i[update]

  def index
    @drafts = UserCode.includes(:codes, :tags).drafts(current_user.id)
  end

  def create
    @code = UserCode.new(user_codes_params)
    @code.codes = codes
    @code.user = current_user
    if @code.draft(params[:tags])
      redirect_to root_path
    else
      render 'codes/new'
    end
  end

  def update
    @code = UserCode.new(user_codes_params)
    @code.codes = codes
    if @code.update_version(params[:id], params[:tags], :draft)
      redirect_to action: :index
    else
      render 'codes/edit'
    end
  end

  def destroy
    @code = UserCode.find(params[:id])
    if current_user != @code.user
      render :index
    elsif @code.destroy
      flash[:success] = t('deleted')
      redirect_to action: :index
    else
      flash.now[:alert] = t('errors.invalid')
      render :index
    end
  end

  private

  def user_codes_params
    params.require(:user_code).permit(
      :title, :description
    )
  end
end

app/controllers/codes/histories_controller.rb
# frozen_string_literal: true

class Codes::HistoriesController < ApplicationController
  before_action :authenticate_user!

  def show
    @histories = UserCode.histories(params[:id])
  end
end

app/controllers/codes/likes_controller.rb
# frozen_string_literal: true

class Codes::LikesController < ApplicationController
  protect_from_forgery except: %i[create destroy]
  before_action :authenticate_user!

  def create
    code = UserCode.find(params[:code_id])
    like = UserCodeLike.new(user: current_user, user_code: code)
    like.save!
    render json: { status: :success }
  rescue StandardError => e
    logger.error e
    render json: { status: :error }
  end

  def destroy
    like = UserCodeLike.find_by(user_code_id: params[:id], user_id: current_user.id)
    like.destroy!
    render json: { status: :success }
  rescue StandardError => e
    logger.error e
    render json: { status: :error }
  end
end

app/controllers/codes_controller.rb
# frozen_string_literal: true

class CodesController < ApplicationController
  include CodePermittable

  before_action :authenticate_user!, except: %i[index show]
  before_action :verify_valid_user, only: %i[update]

  def index
    @latest = UserCode.latest
    @popular = UserCode.popular
    @popular_tags = Tag.popular
  end

  def show
    @code = UserCode.includes(:codes, :user).find(params[:id])
  end

  def new
    @code = UserCode.new
    @code.codes.push(Code.new)
    @tags = Tag.all
  end

  def create
    @code = UserCode.new(user_codes_params)
    @code.codes = codes
    if @code.post(params[:tags])
      redirect_to root_path, success: 'コードの投稿が完了しました'
    else
      flash.now[:alert] = '入力内容に誤りがあります'
      render :new
    end
  end

  def edit
    @tags = Tag.all
    @code = UserCode.includes(:codes).find(params[:id])
    raise Forbidden unless current_user == @code.user

    @code.codes.build if @code.codes.empty?
  end

  def update
    @code = UserCode.new(user_codes_params)
    @code.codes = codes
    if @code.update_version(params[:id], params[:tags], :post)
      # TODO: リダイレクト先を投稿一覧に変える
      redirect_to action: :index
    else
      render :edit
    end
  end

  private

  def user_codes_params
    params[:user_code][:user_id] = current_user.id
    params.require(:user_code).permit(
      :title, :description, :user_id
    )
  end
end

app/helpers/codes/dislikes_helper.rb
# frozen_string_literal: true

module Codes::DislikesHelper
end

app/helpers/codes/drafts_helper.rb
# frozen_string_literal: true

module Codes::DraftsHelper
end

app/helpers/codes/histories_helper.rb
# frozen_string_literal: true

module Codes::HistoriesHelper
end

app/helpers/codes/likes_helper.rb
# frozen_string_literal: true

module Codes::LikesHelper
end

app/helpers/codes_helper.rb
# frozen_string_literal: true

module CodesHelper
  IMAGE_EXT = %w[.png .jpg .gif].freeze

  def languages
    Language.all
  end

  def language_image_path(name)
    IMAGE_EXT.each do |ext|
      path = "icons/#{name}#{ext}"
      return path if image_exists?(path)
    end
    raise "イメージが見つかりませんでした。name:#{name}, ext:#{IMAGE_EXT}"
  end

  private

  def image_exists?(path)
    app = Rails.application
    if Rails.env.production?
      app.assets_manifest.find_sources(path).present?
    else
      app.assets.find_asset(path).present?
    end
  end
end

app/views/codes/drafts/edit.html.slim
#code.uk-container.uk-margin
  = display_flash_messages(@code)

  = form_with model: @code, url: codes_path, id: 'code-form', method: :post, local: true, builder: RefineFormBuilder do |f|
    .title.uk-margin
      = f.label :title, class: 'uk-text-small uk-margin-small-right'
      required-badge
      = f.text_field :title, class: 'uk-input', placeholder: '例）Rubyのfizz_buzzプログラムです'

    .description.uk-margin
      = f.label :description, class: 'uk-text-small uk-margin-small-right'
      required-badge
      = f.text_area :description, class: 'uk-textarea', rows: 5, placeholder: '例）Rubyで作ったfizz_buzzのプログラムです。もう少し簡潔で綺麗な書き方があるかと思うのですが、なかなか思いつきません。どうかご教授いただきたいです。'

    tag-input[
      :autocomplete-tags=tag_hash(@tags).to_json
      :default-tags=tag_hash(@code&.tags&.map(&:name)).to_json
    ]

    code-form.uk-margin[
      new-code=Code.new.to_json
      codes=@code.codes.to_json
      :langs=languages.to_json
      :errors=@code.codes.map(&:errors).map(&:full_messages).to_json
    ]

    .uk-alert-warning[uk-alert]
      a.uk-alert-close[uk-close]
      p
        = "下書きは#{UserCode::DRAFT_LIMIT}件まで登録できます"

    .submit-btn.uk-text-center.uk-margin
      a.uk-button.uk-button-primary[href="#confirm" uk-toggle] 投稿
      button.uk-button.uk-button-default.uk-margin-left[formaction=codes_drafts_path] 下書き保存

#modal
  modal[id="confirm"]
    p.uk-text-center
      | この内容を投稿します。
      br
      | よろしいですか？
    .uk-text-center
      button.uk-button.uk-button-primary.uk-button-small[type="submit" form="code-form"] 投稿
      button.uk-button.uk-button-default.uk-margin-left.uk-button-small.uk-modal-close[type="submit"] キャンセル

app/views/codes/drafts/index.html.slim
.uk-container
  .drafts.uk-margin-top
    ul.uk-tab-right.uk-width-1-4.uk-inline-block.uk-tab[uk-switcher="" uk-tab=""]
      - @drafts.each do |draft|
        li
          a[href="#" aria-expanded="true"]
            .uk-text-emphasis.no-text-transform
              = draft.title
            .uk-text-small.uk-text-muted.uk-text-light
              = l(draft.updated_at)

    ul.uk-switcher.uk-inline-block.uk-width-3-4.vertical-top
      - @drafts.each do |draft|
        li
          .edit-buttons.uk-margin.uk-text-right
            = link_to t('history'), codes_history_path(draft.id), class: 'uk-button uk-button-default uk-margin-right'
            = link_to t('edit'), edit_code_path(id: draft.id), class: 'uk-button uk-button-default uk-margin-right'
            a.uk-button.uk-button-danger[href="#confirm#{draft.id}" uk-toggle] = t('delete')

          article.uk-article
            .heading.uk-background-muted.uk-padding-small
              h1.uk-article-title
                = draft.title

              - draft.tags.each do |tag|
                tag[label=tag.name]

            p.uk-padding-small
              = draft.description

            - draft.codes.each do |code|
              code-area[
                code=code.code
                :code-id=code.id
                is-login=user_signed_in?
                posted-user-icon=current_user.icon_url
                :current-user-id=current_user.id
                :disabled="true"
              ]

          #modal
            modal[id="confirm#{draft.id}"]
              p.uk-text-center
                = t('messages.confirm_before_delete').html_safe
              .uk-text-center
                = link_to t('delete'), codes_draft_path(draft.id), class: 'uk-button uk-button-primary uk-button-small', method: :delete
                button.uk-button.uk-button-default.uk-margin-left.uk-button-small.uk-modal-close[type="submit"]
                  = t('cancel')